Repository namhai2307/CITS3403_GROUP_PROJECT, pull requests merged in 2025-04, with the labels that each got.

#5 Fixed bug issue with button & updated brand name
  homepagestyle.css
  index.html
Labels: bugfix

#7 New Feature: Added structure for each button feature of webpage
  app/__pycache__/__init__.cpython-311.pyc
  app/__pycache__/__init__.cpython-312.pyc
  app/__pycache__/config.cpython-311.pyc
  app/__pycache__/models.cpython-311.pyc
  app/__pycache__/routes.cpython-311.pyc
  app/static/homepagescript.js
  app/static/homepagestyle.css
  app/templates/index.html
Labels: enhancement

#36 Improved login module: switch to blueprint architecture, fix template routing
  app/__init__.py
  app/forms.py
  app/models.py
  app/routes.py
  app/templates/dashboard.html
  app/templates/index.html
  app/templates/login.html
  app/templates/logout.html
  app/templates/sign_up.html
Labels: enhancement

#40 Fixed redirection functionality (refer to Issues #27 & #38)
  app.db
  app/__init__.py
  app/__pycache__/__init__.cpython-311.pyc
  app/__pycache__/config.cpython-311.pyc
  app/__pycache__/forms.cpython-311.pyc
  app/__pycache__/models.cpython-311.pyc
  app/__pycache__/routes.cpython-311.pyc
  app/config.py
  app/routes.py
  app/static/dashboard.css
  app/templates/dashboard.html
  app/templates/index.html
  migrations/README
  migrations/__pycache__/env.cpython-311.pyc
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/__pycache__/ee45834b7423_create_user_table.cpython-311.pyc
  migrations/versions/ee45834b7423_create_user_table.py
Labels: enhancement

#48 Add content inside "index.html"
  app/templates/index.html
Labels: tasks
